### ISSUE TITLE
Hydration Error Relating To Empty Table Tags

### ISSUE THREAD

**Issue by EOEboh** [MananTank/eslint-plugin-validate-jsx-nesting#4]
Hello @MananTank and @gkiely 

Lovely project I must say.
I am raising this issue to highlight the instance of an hydration error popping out when a `<table>` element contains no children during initial rendering. 

Let me explain in code terms: 

 ```<div>
 <table>
   {dynamic.length > 0 &&
   <thead>
      <tr>
         <th>{title1}</th>
      </tr>
      <tr>
         <th>{title2}</th>
      </tr>
      .......
   </thead>
   <tbody>
      <tr>
         <th>
            <div>{dynamic.data1}</div>
         </th>
         <th>
            <div>{dynamic.data2}</div>
         </th>
         .......
      </tr>
   </tbody>
   }
</table>
</div>
```

During initial render, the initial HTML will display as an empty table tag:

```
<div>
   <table></table>
</div>
```
This makes React 18, Nextjs (or any SSR framework)  throw an Hydration error. 

However the fix for this without using a `useEffect` or NoSSR wrapper is to nest the parent `<table>` element inside the conditional. E.g.:
```
<div>
{dynamic.length > 0 &&
<table>
   <thead>
      <tr>
         <th>{title1}</th>
      </tr>
      <tr>
         <th>{title2}</th>
      </tr>
      .......
   </thead>
   <tbody>
      <tr>
         <th>
            <div>{dynamic.data1}</div>
         </th>
         <th>
            <div>{dynamic.data2}</div>
         </th>
         .......
      </tr>
   </tbody>
</table>
}
</div>
```

Please you are free to confirm this, and permit a pull request. If it already exist in the library, then no problems. All good!

**Comment by MananTank** [comment]
Since this is just an ESLint plugin - It can not actually evaluate the conditional logic and figure out the final Virtual DOM structure here. This would require a runtime validation and can not be properly detected by a linter plugin
